name: clean_architecture_cli
description: A simple command line application to generate simple folder and file structure for Flutter Applications
version: 0.1.4+1
homepage: https://github.com/Soufiene-Hmila/clean_architecture_cli.git
documentation: https://github.com/Soufiene-Hmila/clean_architecture_cli.git

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0

executables:
  clean_architecture_cli: